- added files for zc.buildout for easier deployment - changed the setup.py accordingly - corrected all server launch problems, should work directly without fidling around!: no more AttributeError: 'Bottle' object has no attribute 'chosenServer' problems -fixed a few path problems - added handling of SERVERURL/ and SERVERURL without the need to add index.html - corrected a few logging problems here and there